##########################################################
#
# Project: RCM - Denial Management
# Description: Agentic AI based Denial management activities
# Author:  RK (kvrkr866@gmail.com)
# File name: analysis.py
# Purpose: Pydantic models for DenialAnalysis (LLM structured
#          output) and CorrectionPlan generated by the
#          correction planning agent.
#
##########################################################

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


# ------------------------------------------------------------------ #
# Denial analysis (output of analysis agent, LLM structured output)
# ------------------------------------------------------------------ #

class DenialAnalysis(BaseModel):
    """Structured result produced by the LLM-powered analysis agent."""

    claim_id: str
    root_cause: str = Field(..., description="Plain-English root cause of denial")
    carc_interpretation: str = Field(..., description="Meaning of the CARC code in context")
    rarc_interpretation: str = Field(
        default="N/A", description="Meaning of the RARC code if present"
    )
    missing_items: list[str] = Field(
        default_factory=list,
        description="List of missing documentation or information",
    )
    incorrect_items: list[str] = Field(
        default_factory=list,
        description="List of incorrect codes, dates, or fields",
    )
    correction_possible: bool = Field(
        ..., description="Whether the denial can be corrected and resubmitted"
    )
    recommended_action: Literal["resubmit", "appeal", "both", "write_off"] = Field(
        ..., description="Recommended next action"
    )
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="LLM confidence in recommendation"
    )
    reasoning: str = Field(..., description="Full reasoning behind the recommendation")
    denial_category: Literal[
        "timely_filing",
        "medical_necessity",
        "prior_auth",
        "duplicate_claim",
        "coding_error",
        "eligibility",
        "coordination_of_benefits",
        "other",
    ] = Field(default="other")
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)


# ------------------------------------------------------------------ #
# Correction plan (output of correction planning agent)
# ------------------------------------------------------------------ #

class CodeCorrection(BaseModel):
    original_code: str
    corrected_code: str
    code_type: Literal["CPT", "ICD10", "HCPCS", "modifier"]
    reason: str


class DocumentationRequirement(BaseModel):
    document_type: str
    description: str
    is_mandatory: bool = True
    is_available: bool = False
    source: Optional[str] = None  # e.g. "EHR", "Provider office", "Lab"


class CorrectionPlan(BaseModel):
    """Detailed plan for correcting and resubmitting a denied claim."""

    claim_id: str
    plan_type: Literal["resubmission", "appeal", "both"]

    # Coding corrections
    code_corrections: list[CodeCorrection] = Field(default_factory=list)

    # Documentation checklist
    documentation_required: list[DocumentationRequirement] = Field(
        default_factory=list
    )

    # Compliance checks
    compliance_notes: list[str] = Field(default_factory=list)
    regulatory_references: list[str] = Field(default_factory=list)

    # Resubmission instructions
    resubmission_instructions: list[str] = Field(default_factory=list)
    payer_specific_notes: list[str] = Field(default_factory=list)

    # Estimated outcome
    estimated_reimbursement: Optional[float] = None
    success_probability: Optional[float] = Field(None, ge=0.0, le=1.0)

    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def has_code_corrections(self) -> bool:
        return len(self.code_corrections) > 0

    @property
    def missing_documents(self) -> list[DocumentationRequirement]:
        return [d for d in self.documentation_required if not d.is_available]
