##########################################################
#
# Project: RCM - Denial Management
# Description: Agentic AI based Denial management activities
# Author:  RK (kvrkr866@gmail.com)
# File name: appeal.py
# Purpose: Pydantic model for AppealPackage generated by the
#          appeal preparation agent including letter content,
#          evidence bundle, and deadline tracking.
#
##########################################################

from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, Field, computed_field


class SupportingDocument(BaseModel):
    document_name: str
    document_type: str  # e.g. "clinical_note", "auth_letter", "eob_copy"
    description: str
    is_attached: bool = False
    file_path: Optional[str] = None


class AppealLetter(BaseModel):
    """LLM-generated formal appeal letter."""

    recipient_name: str = "Appeals Department"
    recipient_address: Optional[str] = None
    sender_name: str
    sender_npi: Optional[str] = None
    sender_address: Optional[str] = None
    date_of_letter: date = Field(default_factory=date.today)

    # Letter body sections (LLM-generated)
    subject_line: str
    opening_paragraph: str
    denial_summary: str
    clinical_justification: str
    regulatory_basis: str
    closing_paragraph: str
    signature_block: str

    @property
    def full_text(self) -> str:
        """Assembles the complete letter text."""
        return "\n\n".join([
            f"Date: {self.date_of_letter.strftime('%B %d, %Y')}",
            f"To: {self.recipient_name}" +
            (f"\n{self.recipient_address}" if self.recipient_address else ""),
            f"From: {self.sender_name}" +
            (f"\nNPI: {self.sender_npi}" if self.sender_npi else ""),
            f"RE: {self.subject_line}",
            self.opening_paragraph,
            self.denial_summary,
            self.clinical_justification,
            self.regulatory_basis,
            self.closing_paragraph,
            self.signature_block,
        ])


class AppealPackage(BaseModel):
    """Complete appeal submission package for a denied claim."""

    claim_id: str
    payer_id: str
    patient_id: str

    # Appeal letter
    appeal_letter: Optional[AppealLetter] = None

    # Supporting evidence
    supporting_documents: list[SupportingDocument] = Field(default_factory=list)

    # Deadline tracking
    denial_date: Optional[date] = None
    appeal_deadline_days: int = 180
    payer_appeal_portal: Optional[str] = None
    payer_appeal_fax: Optional[str] = None
    payer_appeal_address: Optional[str] = None

    # Payer-specific instructions
    submission_instructions: list[str] = Field(default_factory=list)

    created_at: datetime = Field(default_factory=datetime.utcnow)

    @computed_field
    @property
    def appeal_deadline(self) -> Optional[date]:
        if self.denial_date:
            from datetime import timedelta
            return self.denial_date + timedelta(days=self.appeal_deadline_days)
        return None

    @computed_field
    @property
    def days_until_deadline(self) -> Optional[int]:
        if self.appeal_deadline:
            delta = self.appeal_deadline - date.today()
            return delta.days
        return None

    @property
    def is_urgent(self) -> bool:
        days = self.days_until_deadline
        return days is not None and days <= 30
